export {
  match,
  matchWithDefault,
  matchAsync,
  matchWithDefaultAsync,
  matchAllAsync,
  map,
  mapAll,
  mapAsync,
  fold,
  foldWithDefault,
  foldAsync,
  foldWithDefaultAsync,
  count,
  partition,
  createPipeHandlers,
  createUnion,
  is,
  isUnion,
  UnknownVariantError,
} from './unions';
export type {
  TakeDiscriminant,
  InferUnion,
  Matcher,
  MatcherWithDefault,
  Mapper,
  MapperAll,
  Folder,
  FolderWithDefault,
  AsyncMatcher,
  AsyncMatcherWithDefault,
  AsyncMapper,
  AsyncFolder,
  AsyncFolderWithDefault,
} from './types';
